pom.xml changes for Cloud sql socket factory
averikitsch/langchain4j pull request #2
Opened 2024-12-20 01:13 UTC by nitesh-55

## Issue

Closes #

## Change

## General checklist

- [ ] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

2024-12-26 15:59 UTC, kurtisvg requested changes
It looks like we are adding some exclusions to specified dependencies, but then re-specifying them explicitly higher up.  

My Maven skills are a bit rusty (and maybe you've discussed this with Averi), but I would typically expect [DependencyManagement](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management) to be used to control transient dependencies. Is there a reason that approach wasn't used?

It would be good to include more of a description in the PR as well to capture why the change is being made and the reason behind the design.

2024-12-26 15:59 UTC, kurtisvg commented on langchain4j-cloud-sql-postgres/pom.xml
> +                <exclusion>
nit: Could you run this through a formatter quick? indentation is off in multiple places

2024-12-26 15:59 UTC, kurtisvg commented on langchain4j-cloud-sql-postgres/pom.xml
> +            <artifactId>google-http-client-gson</artifactId>
this exclusion is listed twice -- is that intentional?

2024-12-26 15:59 UTC, kurtisvg commented on langchain4j-cloud-sql-postgres/pom.xml
> +        <version>1.21.0</version>
should this be the latest version?

2025-01-03 23:22 UTC, nitesh-55 commented on langchain4j-cloud-sql-postgres/pom.xml
> +                <exclusion>
done

2025-01-03 23:25 UTC, nitesh-55 commented on langchain4j-cloud-sql-postgres/pom.xml
> +            <artifactId>google-http-client-gson</artifactId>
first one is for  "google-http-client-gson"
and second one for  "google-http-client"

2025-01-03 23:38 UTC, nitesh-55 commented on langchain4j-cloud-sql-postgres/pom.xml
> +        <version>1.21.0</version>
yes, this is the latest version. We get dependency convergence errors for older versions.

2025-01-03 23:45 UTC, nitesh-55 commented
I was following https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc.md to add dependencies for cloud sql socket factory and Maven build failed with that jar version.

Then tried v1.21.0 for cloud sql postgres socket factory as it seemed other versions were not successfully released.

Got dependency convergence errors after that and I was asked to follow
https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html to resolve those.

2025-01-07 18:58 UTC, averikitsch requested changes
A couple of small requests

2025-01-07 18:58 UTC, averikitsch commented on langchain4j-cloud-sql-postgres/pom.xml
> +        <version>1.21.0</version>
We can now upgrade to the latest version

2025-01-07 18:58 UTC, averikitsch commented on langchain4j-cloud-sql-postgres/pom.xml
>              <version>${postgresql.version}</version>
Can we add the version directly here for now instead of using the properties? Thanks!

2025-01-07 18:58 UTC, averikitsch commented on langchain4j-cloud-sql-postgres/pom.xml
> +            </exclusion>
Can you format this file so these are indented? Thanks!

2025-01-07 21:18 UTC, nitesh-55 commented on langchain4j-cloud-sql-postgres/pom.xml
> +            </exclusion>
done

2025-01-08 00:49 UTC, nitesh-55 commented on langchain4j-cloud-sql-postgres/pom.xml
>              <version>${postgresql.version}</version>
done

2025-01-08 01:09 UTC, nitesh-55 commented on langchain4j-cloud-sql-postgres/pom.xml
> +        <version>1.21.0</version>
done

2025-01-08 22:23 UTC, averikitsch approved these changes

2025-01-08 22:23 UTC, merged